### ISSUE TITLE
incorrect repository name

### ISSUE THREAD

**Issue by danmarsden** [adlnet/Moodle-mod_cmi5launch#24]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

**Comment by ADLMeganBohland** [comment]
The repo has been renamed
