### ISSUE TITLE
Messy copyright headers

### ISSUE THREAD

**Issue by danmarsden** [adlnet/Moodle-mod_cmi5launch#29]
This plugin appears to be heavily based on another plugin written by another developer. This should be stated within your readme file at a minimum, and the copyright headers in many of your files should be revised to make this clear as well.

more information on the correct process is here:
https://moodledev.io/general/community/plugincontribution/checklist#copyrights

**Comment by ADLMeganBohland** [comment]
@danmarsden Hey Dan, This plugin did start based off the tin can launch plugin. Some pages like AUview were developed only by me. Although obviously some pages like lib.php has base functions from the original plugin. Should the "based off of" go on ALL the pages? For instance all the classes in '/classes/local' were developed by me and only for this plugin, I want to give credit where it is due, but also don't want to muddle up the original plugin which doesn't use them. Thanks for advice!

**Comment by danmarsden** [comment]
I think the main thing I'm looking for is something in your readme file that states "this plugin was based on the tin can launch plugin created by XXX" 

then you want to make sure the ones that are only yours - (and simple files like version.php etc.) have your copyright header not the author from the tincan launch one.

but I'm unlikely to go digging further than that as part of the review.

**Comment by ADLMeganBohland** [comment]
@danmarsden Hi Dan, I think I found all places where headers needed correction and did so. I added them to Readme as well.
