### ISSUE TITLE
function naming violations

### ISSUE THREAD

**Issue by danmarsden** [adlnet/Moodle-mod_cmi5launch#31]
Many of the functions at the end of: https://github.com/adlnet/cmi5-player-moodle-plugin/blob/main/lib.php and possibly all functions defined in locallib.php violate the function naming guidelines - please see:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#function-names

note this is a blocker for plugins db approval.

**Comment by ADLMeganBohland** [comment]
@danmarsden 
Hi, so instead of starting cmin5launch_ it should be mod_cmi5launch?

**Comment by danmarsden** [comment]
activity plugins are allowed to skip the "mod_" part of the frankenstyle naming but functions like this:
function use_global_cmi5_lrs_settings(

are not allowed.

so either of these would be allowed and follow the guidelines:
function mod_cmi5launch_lrs_settings()
function cmi5launch_lrs_settings()

**Comment by ADLMeganBohland** [comment]
@danmarsden All the incorrect functions have been renamed. Thank you!
