### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by mudrd8mz** [adlnet/Moodle-mod_cmi5launch#44]
When installing 2024022015 to Moodle 4.3, I am getting:

```
Warning: Undefined variable $course in .../moodle/mod/cmi5launch/db/install.php on line 28

Warning: Undefined variable $cm in .../moodle/mod/cmi5launch/db/install.php on line 28
```

**Comment by ADLMeganBohland** [comment]
@mudrd8mz We are now on version 2024061115 and I believe this has been resolved, however I want to test and verify. You get this error when upgrading moodle?

**Comment by mudrd8mz** [comment]
I used the most recent version from the plugins directory. That is what we (and all other Moodle admins out there) will do normally. As I said, I got this when installing the plugin to the site.

**Comment by ADLMeganBohland** [comment]
@mudrd8mz Thank you so much! I have never done this and didn't realize I needed to update the plugin directory I saw the source code link, and thought that was it! I will upload there so you and other admins have access to the newer versions. I apologize for the confusion.

**Comment by ADLMeganBohland** [comment]
The code has been updated and newest version put in place
