### ISSUE TITLE
Better handle user input errors / empty fields

### ISSUE THREAD

**Issue by mudrd8mz** [adlnet/Moodle-mod_cmi5launch#45]
When the module instance form is submitted with default (empty) values, the next screen dies with fatal error messages.

This seems to be a consequence of leaving the endpoint URL empty, which is something that the form allows you to do. I think there might be more "user friendly" way of communicating this rather than "Exception - array_key_exists(): Argument #2 ($array) must be of type array, null given"

![image](https://github.com/user-attachments/assets/43637bd2-e7ce-4d0e-9d73-d214e30d198c)

**Comment by ADLMeganBohland** [comment]
Hi, @mudrd8mz , Thanks for the input. I am currently working on creating specialized exception messages to not only fail more gracefully but try to capture what went wrong and give better info to the user. I will close this issue out when it's done.

**Comment by ADLMeganBohland** [comment]
I forgot to close this issue, this should be handled in the pushed branch 'better-hanlde-errors'
